name: make img

on:
  watch:
    types: [started]

jobs:
  make_bigsur:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: chekcout
      uses: actions/checkout@master
    
    - name: make
      run: |
        cd scripts/bigsur
        make BigSur-recovery.img
        make BigSur-full.img

    - name: upload BigSur-recovery
      uses: actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: bigSur-recovery
        path: scripts/bigsur/BigSur-recovery.img

    - name: upload BigSur-full
      uses: actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: bigSur-full
        path: scripts/bigsur/BigSur-full.img

  make_monterey:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: make
      run: |
        cd scripts/monterey
        make Monterey-recovery.img
        make Monterey-full.img

    - name: upload Monterey-recovery
      uses: actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: monterey-recovery
        path: |
          scripts/monterey/Monterey-recovery.img
          scripts/monterey/Monterey-full.img

    - name: upload Monterey-full
      uses: actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: monterey-full
        path: scripts/monterey/Monterey-full.img 
                   
  make_ventura:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: make
      run: |
        cd scripts/ventura
        make Ventura-recovery.img
        make Ventura-full.img

    - name: upload Ventura-recovery
      uses: actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: ventura-recovery
        path: scripts/ventura/Ventura-recovery.img
         
    - name: upload Ventura-full
      uses: actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: ventura-full
        path: scripts/ventura/Ventura-full.img     